sequenceDiagram
    participant H as Human
    participant A as AI

    note over H,A: Goal Setting
    H ->> A: Select [statement]

    note over H,A: Data Preparation
    A ->> A: Generate [recommendation]

    note over H,A: Visualization
    A ->> H: Present [options]
    H ->> A: Choose [context]
    A ->> A: Match [data]
    A ->> H: Visualize [context]