sequenceDiagram
    participant H as Human
    participant A as AI

    note over H,A: Goal Setting
    H ->> A: Set [goal]

    note over H,A: Data Preparation
    A ->> A: Discover [subgroup]

    note over H,A: Visualization
    A ->> H: Show [ranking]

    note over H,A: Insight Synthesis
    H ->> A: Re-rank [criteria]
    H ->> A: Edit [definition]
    A ->> H: Update [metrics]
    A ->> H: Map [overlap]
    H ->> A: Curate [subgroup]