sequenceDiagram
    participant H as Human
    participant A as AI

    note over H,A: Goal Setting
    H ->> A: Upload [dataset]

    note over H,A: Data Preparation
    A ->> H: Recommend [charts]

    note over H,A: Visualization
    alt Edit
        H ->> A: Modify [view]
        A ->> H: Update [suggestion]
    else Accept
        H ->> A: Confirm [dashboard]
    end

    note over H,A: Insight Synthesis
    A ->> H: Save [log]