sequenceDiagram
    participant H as Human
    participant A as AI

    note over H,A: Goal Setting
    H ->> A: Specify [design]

    note over H,A: Data Preparation
    A ->> A: Compile [graph]
    A ->> H: Ask [question]
    H ->> A: Provide [answer]

    note over H,A: Insight Synthesis
    A ->> A: Infer [model]
    A ->> H: Output [code]