sequenceDiagram 
   note over H,A: goal setting 
   A ->> H: Ask [question] 
   A ->> H: Explain [status] 

   note over H,A: insight synthesis 
   A ->> H: Recommend [labels] 
   H ->> A: Respond [feedback] 
   A ->> A: Update [model]